import { useState } from 'react'
import { COLORS } from '../theme'
import { Circle, Square, Triangle } from '../components/Decorations'
import FadeIn from '../components/FadeIn'
import ContactCTA from '../components/ContactCTA'

// ─── Page Intro ───────────────────────────────────────────────────────────
function PageIntro() {
  return (
    <section
      className="pt-20 sm:pt-24 border-b-4 relative overflow-hidden"
      style={{ borderColor: COLORS.black, backgroundColor: COLORS.bg }}
    >
      <Circle color={COLORS.yellow} size={300} className="-top-20 -right-20 opacity-10" />
      <Square color={COLORS.blue} size={160} rotate className="-bottom-10 -left-10 opacity-10" />
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20 lg:py-28 relative z-10">
        <FadeIn>
          <p
            className="text-xs sm:text-sm uppercase tracking-[0.3em] mb-3"
            style={{ fontWeight: 700, color: COLORS.red }}
          >
            Career
          </p>
          <h1
            className="text-5xl sm:text-6xl lg:text-8xl uppercase leading-[0.9] mb-6"
            style={{ fontWeight: 900, color: COLORS.black, letterSpacing: "-0.04em" }}
          >
            Experience
          </h1>
          <p
            className="text-base sm:text-lg leading-relaxed max-w-2xl"
            style={{ fontWeight: 500, color: "#555" }}
          >
            A career built across experimental biology, computational science, and product-scale infrastructure.
          </p>
        </FadeIn>
      </div>
    </section>
  )
}

// ─── Professional Experience ──────────────────────────────────────────────
function ProfessionalExperience() {
  const roles = [
    {
      accent: COLORS.blue,
      title: "Senior Structural Bioinformatician",
      org: "Protein Data Bank in Europe (EMBL-EBI) · Google DeepMind Collaboration",
      dates: "January 2023 to Present",
      location: "Hinxton, Cambridge",
      body: "Lead Bioinformatician and Business Analyst steering the scientific roadmap for AlphaFold DB, the world's most comprehensive open-access database of predicted protein structures. I architect high-throughput pipelines, translate user needs into actionable features, and conduct literature reviews to identify workflow gaps that AlphaFold DB can address through targeted development and external collaboration.",
      bullets: [
        "Developed the AFDB-Integration Toolkit, a programmatic framework for converting predicted models from AlphaFold into the data and formats required for database integration. Now the core system enabling third-party dataset ingestion into AlphaFold DB.",
        "Leading the ongoing integration of community datasets into AlphaFold DB for the first time, including high-value datasets for microbial proteins, viral proteins, and kinetoplastid parasites generated by specialist communities, with an ongoing collaboration with Nvidia introducing predicted homodimers at scale (first-author, 2026).",
        "Feature owner of TED domain annotations. Delivered the complete ingestion-to-UI pipeline that now overlays domain boundaries on every AlphaFold model page, providing researchers with immediate structural context to interpret domain boundaries alongside the PAE matrix and assess model quality for hypothesis generation.",
        "Led the integration of Foldseek and cluster members table to help users navigate protein structure space, alongside BLAST search integration, designing scalable pipelines using VMs, Redis, Celery, and Python tooling to support real-time and precomputed querying.",
        "Represented AlphaFold DB globally, presenting product capabilities and user workflows at 15+ conferences and training courses, including ISMB-ECCB 2024 (the world's largest bioinformatics conference) and the INSERM Workshop 271 in Bordeaux.",
      ],
    },
    {
      accent: COLORS.red,
      title: "Team Lead & Bioinformatician, PETase Tournament",
      org: "The Align Foundation · Open-Science Protein Engineering Competition",
      dates: "September 2025 to Present",
      location: "Remote",
      body: "Participant in a global open-science benchmark for AI-guided enzyme engineering, paired with high-throughput experimental validation. Leading development of supervised ML models to predict PETase activity from competition-provided amino acid sequences, including literature mining, training dataset curation, and benchmarking multiple model architectures. Building hands-on experience in machine learning and protein design through applied competition work.",
      bullets: null,
    },
    {
      accent: COLORS.yellow,
      title: "PhD Researcher, Structural Bioinformatics",
      org: "University of Dundee · Wellcome Trust 4-Year Programme",
      dates: "September 2017 to 2022",
      location: "Dundee, UK",
      body: "Developed a general method for studying the function and evolution of repeat proteins using human population variation and protein structural data. Built a semi-automated Python pipeline for interactive analysis in Jupyter notebooks: retrieving protein annotations, running sequence analysis (Jalview) and human population variant analysis, and performing structural analysis (UCSF ChimeraX). Conducted statistical analyses using SciPy and Scikit-learn with independent data visualisation in Matplotlib. Contributed research findings to publications, seminars, and international conferences.",
      bullets: null,
    },
  ]

  return (
    <section
      className="border-b-4 py-16 sm:py-20 lg:py-28 px-4 sm:px-6 lg:px-8"
      style={{ borderColor: COLORS.black, backgroundColor: COLORS.bg }}
    >
      <div className="max-w-5xl mx-auto">
        <FadeIn>
          <p
            className="text-xs sm:text-sm uppercase tracking-[0.3em] mb-3"
            style={{ fontWeight: 700, color: COLORS.red }}
          >
            Work History
          </p>
          <h2
            className="text-3xl sm:text-4xl lg:text-6xl uppercase leading-[0.9] mb-12 lg:mb-16"
            style={{ fontWeight: 900, color: COLORS.black, letterSpacing: "-0.04em" }}
          >
            Professional
            <br />
            <span style={{ color: COLORS.blue }}>Experience</span>
          </h2>
        </FadeIn>

        <div className="space-y-8">
          {roles.map((role, i) => (
            <FadeIn key={i} delay={i * 150}>
              <div
                className="bg-white border-4 p-6 sm:p-8 relative"
                style={{
                  borderColor: COLORS.black,
                  boxShadow: `6px 6px 0px 0px ${COLORS.black}`,
                }}
              >
                {/* Left accent bar */}
                <div className="absolute top-0 left-0 w-2 h-full" style={{ backgroundColor: role.accent }} />

                <div className="pl-4">
                  {/* Header */}
                  <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-2 mb-4">
                    <div>
                      <h3
                        className="text-xl sm:text-2xl uppercase leading-tight mb-1"
                        style={{ fontWeight: 900, color: COLORS.black, letterSpacing: "-0.02em" }}
                      >
                        {role.title}
                      </h3>
                      <p className="text-sm" style={{ fontWeight: 700, color: role.accent }}>
                        {role.org}
                      </p>
                    </div>
                    <div className="text-right shrink-0">
                      <p className="text-xs uppercase tracking-widest" style={{ fontWeight: 700, color: "#888" }}>
                        {role.dates}
                      </p>
                      <p className="text-xs uppercase tracking-widest" style={{ fontWeight: 500, color: "#aaa" }}>
                        {role.location}
                      </p>
                    </div>
                  </div>

                  {/* Body */}
                  <p className="text-sm sm:text-base leading-relaxed mb-4" style={{ fontWeight: 500, color: "#444" }}>
                    {role.body}
                  </p>

                  {/* Bullets */}
                  {role.bullets && (
                    <ul className="space-y-3">
                      {role.bullets.map((b, j) => (
                        <li key={j} className="flex gap-3">
                          <span
                            className="shrink-0 mt-2 w-2 h-2 rounded-full"
                            style={{ backgroundColor: role.accent }}
                          />
                          <p className="text-sm sm:text-base leading-relaxed" style={{ fontWeight: 500, color: "#444" }}>
                            {b}
                          </p>
                        </li>
                      ))}
                    </ul>
                  )}
                </div>
              </div>
            </FadeIn>
          ))}
        </div>
      </div>
    </section>
  )
}

// ─── Skills & Technologies ────────────────────────────────────────────────
function Skills() {
  const groups = [
    {
      label: "Structural Biology & Bioinformatics",
      accent: COLORS.blue,
      items: ["AlphaFold DB", "BLAST", "Foldseek", "Biopython", "Jalview", "ChimeraX", "TED annotations"],
      dashed: false,
    },
    {
      label: "Programming & Infrastructure",
      accent: COLORS.red,
      items: ["Python", "Redis", "Celery", "Jupyter", "GCP", "Nextflow", "VMs"],
      dashed: false,
    },
    {
      label: "Data Science & Analysis",
      accent: COLORS.yellow,
      items: ["SciPy", "Scikit-learn", "Matplotlib", "Pandas", "Statistical analysis"],
      dashed: false,
    },
    {
      label: "Domain Expertise",
      accent: COLORS.blue,
      items: ["Structural Biology", "Repeat Proteins", "Enzyme Engineering", "Population Genetics"],
      dashed: false,
    },
    {
      label: "Building Toward",
      accent: "#888",
      items: ["Machine Learning for Biology", "Protein Design", "Agentic Workflows", "Notebook-Driven Development"],
      dashed: true,
    },
  ]

  return (
    <section
      className="border-b-4 py-16 sm:py-20 lg:py-28 px-4 sm:px-6 lg:px-8 relative overflow-hidden"
      style={{ borderColor: COLORS.black, backgroundColor: COLORS.blue }}
    >
      <Triangle color="#fff" size={200} className="-top-8 -right-8 opacity-10" />
      <Circle color={COLORS.yellow} size={160} className="-bottom-16 -left-16 opacity-10" />

      <div className="max-w-5xl mx-auto relative z-10">
        <FadeIn>
          <p
            className="text-xs sm:text-sm uppercase tracking-[0.3em] mb-3"
            style={{ fontWeight: 700, color: COLORS.yellow }}
          >
            Toolkit
          </p>
          <h2
            className="text-3xl sm:text-4xl lg:text-6xl uppercase leading-[0.9] mb-12 lg:mb-16"
            style={{ fontWeight: 900, color: "#fff", letterSpacing: "-0.04em" }}
          >
            Skills &amp;
            <br />
            Technologies
          </h2>
        </FadeIn>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
          {groups.map((g, i) => (
            <FadeIn key={i} delay={i * 100}>
              <div
                className="bg-white border-4 p-5 sm:p-6"
                style={{
                  borderColor: g.dashed ? "#aaa" : COLORS.black,
                  boxShadow: g.dashed ? "none" : `6px 6px 0px 0px ${COLORS.black}`,
                  borderStyle: g.dashed ? "dashed" : "solid",
                  opacity: g.dashed ? 0.85 : 1,
                }}
              >
                <div className="flex items-center gap-2 mb-4">
                  <div
                    className="w-3 h-3 rounded-full"
                    style={{ backgroundColor: g.accent }}
                  />
                  <p
                    className="text-xs uppercase tracking-widest"
                    style={{ fontWeight: 700, color: g.dashed ? "#888" : COLORS.black }}
                  >
                    {g.label}
                  </p>
                </div>
                <div className="flex flex-wrap gap-2">
                  {g.items.map((item, j) => (
                    <span
                      key={j}
                      className="px-3 py-1 text-xs uppercase tracking-wider border-2"
                      style={{
                        fontWeight: 700,
                        borderColor: g.dashed ? "#ccc" : g.accent,
                        color: g.dashed ? "#aaa" : g.accent,
                        borderStyle: g.dashed ? "dashed" : "solid",
                      }}
                    >
                      {item}
                    </span>
                  ))}
                </div>
              </div>
            </FadeIn>
          ))}
        </div>
      </div>
    </section>
  )
}

// ─── Education ────────────────────────────────────────────────────────────
function Education() {
  const degrees = [
    {
      degree: "PhD, Structural Bioinformatics",
      programme: "Wellcome Trust 4-Year Programme",
      institution: "University of Dundee, School of Life Sciences",
      dates: "2017 to 2022",
      accent: COLORS.yellow,
      shape: "square",
    },
    {
      degree: "BSc (Hons) Molecular Genetics, First Class Honours",
      programme: null,
      institution: "University of Dundee, School of Life Sciences",
      dates: "2014 to 2017",
      accent: "#fff",
      shape: "circle",
    },
  ]

  return (
    <section
      className="border-b-4 py-16 sm:py-20 lg:py-28 px-4 sm:px-6 lg:px-8 relative overflow-hidden"
      style={{ borderColor: COLORS.black, backgroundColor: COLORS.red }}
    >
      <Square color={COLORS.yellow} size={180} rotate className="-top-10 -right-10 opacity-15" />

      <div className="max-w-5xl mx-auto relative z-10">
        <FadeIn>
          <p
            className="text-xs sm:text-sm uppercase tracking-[0.3em] mb-3"
            style={{ fontWeight: 700, color: COLORS.yellow }}
          >
            Academic Background
          </p>
          <h2
            className="text-3xl sm:text-4xl lg:text-6xl uppercase leading-[0.9] mb-12 lg:mb-16"
            style={{ fontWeight: 900, color: "#fff", letterSpacing: "-0.04em" }}
          >
            Education
          </h2>
        </FadeIn>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
          {degrees.map((d, i) => (
            <FadeIn key={i} delay={i * 150}>
              <div
                className="bg-white border-4 p-6 sm:p-8 relative h-full"
                style={{
                  borderColor: COLORS.black,
                  boxShadow: `6px 6px 0px 0px ${COLORS.black}`,
                }}
              >
                <div className="absolute top-0 left-0 w-full h-2" style={{ backgroundColor: d.accent }} />
                <div
                  className="absolute top-4 right-4 w-3 h-3"
                  style={{
                    backgroundColor: d.accent === "#fff" ? COLORS.red : d.accent,
                    borderRadius: d.shape === "circle" ? "50%" : "0",
                  }}
                />
                <p
                  className="text-xs uppercase tracking-widest mb-3 mt-2"
                  style={{ fontWeight: 700, color: "#888" }}
                >
                  {d.dates}
                </p>
                <h3
                  className="text-lg sm:text-xl uppercase leading-tight mb-2"
                  style={{ fontWeight: 900, color: COLORS.black, letterSpacing: "-0.02em" }}
                >
                  {d.degree}
                </h3>
                {d.programme && (
                  <p className="text-sm mb-1" style={{ fontWeight: 700, color: COLORS.blue }}>
                    {d.programme}
                  </p>
                )}
                <p className="text-sm" style={{ fontWeight: 500, color: "#666" }}>
                  {d.institution}
                </p>
              </div>
            </FadeIn>
          ))}
        </div>
      </div>
    </section>
  )
}

// ─── Awards & Recognition ─────────────────────────────────────────────────
function Awards() {
  const awards = [
    {
      title: "The Undergraduate Awards 2017",
      subtitle: "Highly Commended, Life Sciences",
      body: "Ranked in the top 10% of 6,432 submissions from 299 institutions across 47 countries, for work characterising mutant PML-RARα variants from relapsed leukaemia patients.",
      accent: COLORS.yellow,
    },
    {
      title: "Dean's Scholarship Award",
      subtitle: "School of Life Sciences, University of Dundee",
      body: "Awarded by the School of Life Sciences Learning & Teaching, University of Dundee, in recognition of overall excellence in academic performance.",
      accent: COLORS.blue,
    },
  ]

  return (
    <section
      className="border-b-4 py-16 sm:py-20 lg:py-28 px-4 sm:px-6 lg:px-8 relative overflow-hidden"
      style={{ borderColor: COLORS.black, backgroundColor: COLORS.bg }}
    >
      <Circle color={COLORS.red} size={200} className="-bottom-16 -right-16 opacity-8" />

      <div className="max-w-5xl mx-auto relative z-10">
        <FadeIn>
          <p
            className="text-xs sm:text-sm uppercase tracking-[0.3em] mb-3"
            style={{ fontWeight: 700, color: COLORS.blue }}
          >
            Recognition
          </p>
          <h2
            className="text-3xl sm:text-4xl lg:text-6xl uppercase leading-[0.9] mb-12 lg:mb-16"
            style={{ fontWeight: 900, color: COLORS.black, letterSpacing: "-0.04em" }}
          >
            Awards &amp;
            <br />
            Recognition
          </h2>
        </FadeIn>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
          {awards.map((a, i) => (
            <FadeIn key={i} delay={i * 150}>
              <div
                className="bg-white border-4 p-6 sm:p-8 relative h-full"
                style={{
                  borderColor: COLORS.black,
                  boxShadow: `6px 6px 0px 0px ${COLORS.black}`,
                }}
              >
                <div className="absolute top-0 left-0 w-full h-2" style={{ backgroundColor: a.accent }} />
                <h3
                  className="text-lg sm:text-xl uppercase leading-tight mb-1 mt-2"
                  style={{ fontWeight: 900, color: COLORS.black, letterSpacing: "-0.02em" }}
                >
                  {a.title}
                </h3>
                <p className="text-sm mb-3" style={{ fontWeight: 700, color: a.accent }}>
                  {a.subtitle}
                </p>
                <p className="text-sm sm:text-base leading-relaxed" style={{ fontWeight: 500, color: "#555" }}>
                  {a.body}
                </p>
              </div>
            </FadeIn>
          ))}
        </div>
      </div>
    </section>
  )
}

// ─── Testimonial ──────────────────────────────────────────────────────────
function Testimonial() {
  const [expanded, setExpanded] = useState(false)

  const shortQuote = "Maxim is a brilliant, curious, open-minded bioinformatician who constantly explores and comes up with innovative ideas and approaches."
  const fullQuote = "Maxim is a brilliant, curious, open-minded bioinformatician who constantly explores and comes up with innovative ideas and approaches. His contributions are essential to enriching the AlphaFold Protein Structure Database with new, invaluable data that continues to benefit researchers worldwide. Wherever Maxim goes next, they will gain a personable, curious and innovative team member who will pioneer novel solutions to complex scientific problems."

  return (
    <section
      className="border-b-4 py-16 sm:py-20 lg:py-28 px-4 sm:px-6 lg:px-8 relative overflow-hidden"
      style={{ borderColor: COLORS.black, backgroundColor: COLORS.blue }}
    >
      <Triangle color="#fff" size={160} className="-top-4 -left-8 opacity-10" />
      <Square color={COLORS.yellow} size={120} rotate className="-bottom-8 -right-8 opacity-15" />

      <div className="max-w-3xl mx-auto relative z-10">
        <FadeIn>
          <p
            className="text-xs sm:text-sm uppercase tracking-[0.3em] mb-10"
            style={{ fontWeight: 700, color: COLORS.yellow }}
          >
            What Others Say
          </p>
        </FadeIn>

        <FadeIn delay={100}>
          <div
            className="border-4 p-6 sm:p-10 relative"
            style={{
              borderColor: "#fff",
              backgroundColor: "rgba(255,255,255,0.08)",
              boxShadow: `6px 6px 0px 0px ${COLORS.yellow}`,
            }}
          >
            <div className="absolute -top-5 left-6">
              <span className="text-6xl leading-none" style={{ fontWeight: 900, color: COLORS.yellow }}>"</span>
            </div>

            <p
              className="text-base sm:text-lg lg:text-xl leading-relaxed pt-4 mb-6"
              style={{ fontWeight: 500, color: "#fff" }}
            >
              {expanded ? fullQuote : shortQuote}
              {!expanded && (
                <span style={{ color: COLORS.yellow }}> ...</span>
              )}
            </p>

            <button
              onClick={() => setExpanded(!expanded)}
              className="text-xs uppercase tracking-widest border-b-2 pb-0.5 transition-opacity duration-200 hover:opacity-70"
              style={{ fontWeight: 700, color: COLORS.yellow, borderColor: COLORS.yellow }}
            >
              {expanded ? "Show less" : "Read full quote"}
            </button>

            <div className="mt-8 pt-6 border-t" style={{ borderColor: "rgba(255,255,255,0.3)" }}>
              <p className="text-sm uppercase tracking-widest" style={{ fontWeight: 700, color: "#fff" }}>
                Mihaly Varadi
              </p>
              <p className="text-xs uppercase tracking-widest mt-1" style={{ fontWeight: 500, color: "rgba(255,255,255,0.6)" }}>
                Former PDBe Coordinator, EMBL-EBI
              </p>
            </div>
          </div>
        </FadeIn>
      </div>
    </section>
  )
}

// ─── Page ────────────────────────────────────────────────────────────────
export default function Experience() {
  return (
    <>
      <PageIntro />
      <ProfessionalExperience />
      <Skills />
      <Education />
      <Awards />
      <Testimonial />
      <ContactCTA />
    </>
  )
}
